"""
  Generated by Eclipse Cyclone DDS idlc Python Backend
  Cyclone DDS IDL version: v11.0.1
  Module: HandModule
  IDL file: Hand.idl

"""

from dataclasses import dataclass
from enum import auto
from typing import TYPE_CHECKING, Optional

import cyclonedds.idl as idl
import cyclonedds.idl.annotations as annotate
import cyclonedds.idl.types as types

# root module import for resolving types
import teleop.robot_control.prensilia_mia_hand


@dataclass
@annotate.final
@annotate.autoid("sequential")
class HandMsg(idl.IdlStruct, typename="HandModule.HandMsg"):
    thumb: types.int32
    index: types.int32
    middle: types.int32


